name: Build with OpenSSL 3
# This machine tests building the software on a both 32 and 64 Windows architecture.

on: [push]

jobs:

  ubuntu2004:
    name: Build Ubuntu 20.04 OpenSSL 3.0
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          set -x
          sudo apt -q update
          sudo apt install libpcsclite-dev gengetopt help2man libedit-dev libssl-dev libcurl4-openssl-dev libusb-1.0-0-dev cmake perl

          cd $GITHUB_WORKSPACE
          mkdir openssl_3.0.0_installed
          curl -L -O "https://www.openssl.org/source/openssl-3.0.0.tar.gz"
          tar xfz openssl-3.0.0.tar.gz
          cd openssl-3.0.0
          ./Configure shared no-ssl2 no-ssl3 --prefix=$GITHUB_WORKSPACE/openssl_3.0.0_installed
          make all install_sw VERSION="3.0.0"

      - name: Build
        run: |
          set -e -o pipefail
          set -x

          export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/openssl_3.0.0_installed/lib64/pkgconfig
          mkdir build; cd build
          cmake .. -DWITHOUT_MANPAGES=1
          make

      - name: Test
        run: |
          wget -q https://github.com/square/ghostunnel/releases/download/v1.3.1/ghostunnel-v1.3.1-$(uname -s | tr '[:upper:]' '[:lower:]')-amd64-with-pkcs11 -O /tmp/ghostunnel
          chmod +x /tmp/ghostunnel
          openssl aes-256-cbc -k "$tlspwd" -md sha256 -in ./.ci/client-combined.pem.enc -out ./.ci/client-combined.pem -d
          /tmp/ghostunnel client --listen localhost:12345 --target hsm-connector01.sthlm.in.yubico.org:8443 --keystore ./.ci/client-combined.pem --cacert ./.ci/server-crt.pem 2>/dev/null &
          sleep 3
          DEFAULT_CONNECTOR_URL=$(curl -s http://localhost:12345/dispatcher/request)
          test -n "$DEFAULT_CONNECTOR_URL" || (echo "Unable to obtain a connector URL, aborting"; exit 1)
          echo $DEFAULT_CONNECTOR_URL
          echo "DEFAULT_CONNECTOR_URL=$DEFAULT_CONNECTOR_URL" >> $GITHUB_ENV

          ./src/yubihsm-shell --connector "$DEFAULT_CONNECTOR_URL" -p password -a reset


  macos:
    name: Build MacOS OpenSSL 3
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          set -e -o pipefail
          set -x

          brew install cmake gengetopt help2man libedit libusb openssl pkg-config swig truncate

          ls -l /usr/local/opt/openssl

          export PKG_CONFIG_PATH=/usr/local/opt/openssl@3/lib/pkgconfig

          pwd
          mkdir build; cd build
          cmake ..
          make

      - name: Test
        run: |
          wget -q https://github.com/square/ghostunnel/releases/download/v1.3.1/ghostunnel-v1.3.1-$(uname -s | tr '[:upper:]' '[:lower:]')-amd64-with-pkcs11 -O /tmp/ghostunnel
          chmod +x /tmp/ghostunnel
          openssl aes-256-cbc -k "$tlspwd" -md sha256 -in ./.ci/client-combined.pem.enc -out ./.ci/client-combined.pem -d
          /tmp/ghostunnel client --listen localhost:12345 --target hsm-connector01.sthlm.in.yubico.org:8443 --keystore ./.ci/client-combined.pem --cacert ./.ci/server-crt.pem 2>/dev/null &
          sleep 3
          DEFAULT_CONNECTOR_URL=$(curl -s http://localhost:12345/dispatcher/request)
          test -n "$DEFAULT_CONNECTOR_URL" || (echo "Unable to obtain a connector URL, aborting"; exit 1)
          echo $DEFAULT_CONNECTOR_URL
          echo "DEFAULT_CONNECTOR_URL=$DEFAULT_CONNECTOR_URL" >> $GITHUB_ENV

          ./src/yubihsm-shell --connector "$DEFAULT_CONNECTOR_URL" -p password -a reset
