name: Build with OpenSSL 3
# This machine tests building the software on a both 32 and 64 Windows architecture.

on: [push]

jobs:

  ubuntu2004:
    name: Build Ubuntu 20.04 OpenSSL 3.0
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          set -x
          sudo apt -q update
          sudo apt install libpcsclite-dev gengetopt help2man libedit-dev libssl-dev libcurl4-openssl-dev libusb-1.0-0-dev cmake

          cd $GITHUB_WORKSPACE
          mkdir openssl_3.0.0_installed
          curl -L -O "https://www.openssl.org/source/openssl-3.0.0.tar.gz"
          tar xfz openssl-3.0.0.tar.gz
          cd openssl-3.0.0
          ./Configure shared no-ssl2 no-ssl3 --prefix=$GITHUB_WORKSPACE/openssl_3.0.0_installed
          make all install_sw VERSION="3.0.0"

      - name: Build release package
        run: |
          set -e -o pipefail
          set -x

          pwd
          ls $GITHUB_WORKSPACE/openssl_3.0.0_installed
          export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/openssl_3.0.0_installed/lib64/pkgconfig
          mkdir build; cd build
          cmake ..
          make


  macos:
    name: Build MacOS
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          set -e -o pipefail
          set -x

          brew install openssl
          ls /usr/local/opt
          ls /usr/local/opt/openssl
          ls /usr/local/opt/openssl/lib

          export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

          openssl version

          pwd
          mkdir build; cd build
          cmake ..
          make
