name: Build with OpenSSL 3
# This machine tests building the software on a both 32 and 64 Windows architecture.

on: [push]

jobs:

  source:
    name: Build dist with Linux
    runs-on: ubuntu-latest
    env:
      VERSION: 2.3.0
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          set -x
          sudo apt -q update
          sudo apt install libpcsclite-dev gengetopt help2man libedit-dev libcurl4-openssl-dev libssl-dev libusb-1.0-0-dev
      - name: Create tar.gz
        run: |
          set -x
          ./resources/make_src_dist.sh $VERSION
          cd ..
          mkdir artifact
          mv $GITHUB_WORKSPACE/yubihsm-shell-$VERSION.tar.gz artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubihsm-shell-src
          path: ../artifact

  ubuntu2004:
    name: Build Ubuntu 20.04 OpenSSL 3.0
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          set -x
          sudo apt -q update
          sudo apt install libpcsclite-dev gengetopt help2man libedit-dev libssl-dev libcurl libusb-1.0-0-dev cmake

          cd $GITHUB_WORKSPACE
          mkdir openssl_3.0.0_installed
          curl -L -O "https://www.openssl.org/source/openssl-3.0.0.tar.gz"
          tar xfz openssl-3.0.0.tar.gz
          cd openssl-3.0.0
          ./Configure shared no-ssl2 no-ssl3 --prefix=$GITHUB_WORKSPACE/openssl_3.0.0_installed
          make all install_sw VERSION="3.0.0"

      - name: Build release package
        run: |
          set -e -o pipefail
          set -x

          pwd
          ls $GITHUB_WORKSPACE/openssl_3.0.0_installed
          export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/openssl_3.0.0_installed/lib64/pkgconfig
          mkdir build; cd build
          cmake ..
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: yubihsm-shell-ubuntu2004-amd64
          path: artifact
